export const Url = "https://dev.petzi.shop";
// export const Url = "https://petzi.iran.liara.run";
// export const Url = "http://192.168.1.118:8000";
export const baseUrl = `${Url}/api/V1`;
export const imageUrl = `${Url}/`;
export const imageUrlBase = `${Url}/images/contents/`;
export const IMAGE_URL = (path) => `${Url}/${path}`;

export const apiRoutes = {
  AU1: "/business/login/code/send",
  AU2: "/business/login/code/verify",
  AU3: "/register",
  AU4: "/user",
  AU5: "/user/national-card/upload",
  AU6: "/user/legal/person",
  AU7: "/business/login",
  CHECK_NUM: "/business/login/check-mobile-number",
  LOGOUT: "/business/logout",
  AU8: "/business/login/password/submit",
  AU9: "/business/login/password/verify",
  BASE_CONTENT: function (key_name) {
    return `/Base/Category?content_name=${key_name}`;
  },
  PROVINCES: "/Base/Provinces",
  WALLET1: "/user/wallet",
  WALLET2: "/user/wallet/gold/qr-code",
  WALLET3: "/user/cash-request",
  PAY1: "/payment/request",
  TRA1: "/gold/buy",
  TRA2: "/gold/sell",
  TRA3: "/gold/transfer",
  TRA4: "/user/invoices",
  TRA5: (id) => `/user/invoices/${id}/receipt`,
  TRA6: (id) => `/user/invoices/${id}/view/request`,
  REGISTER_STEP: (number) => `/business/update?register_step=${number}`,
  TURNOVERS1: "/user/turnovers",
  TURNOVERS2: "/user/gold/turnovers",
  UPLOAD_TEMP_FILE: "/upload/file/temp",
  GOLD_PRICE: "/gold/price",
  ROLE1: "/roles",
  ROLE2: "/user/role/change",
  ROLE3: "/user/roles",
  ROLE4: (id) => `/user/roles/${id}/cancel`,
  CITIES: (id) => `/city/${id}`,
  GET_PRODUCT: (id) => `/business/products/${id}`,
  ANSWER_COMMENT: (id) => `/business/comments/${id}`,
  UNITS: (key) => `/units?key=${key}`,
  SESSIONS: "/user/login/logs",
  OPEND_AND_CLOSE: "/business/daily-discounts/time/get",
  BUSINESS_PROFILE: "/business/profile",
  UPLOAD: "/upload-files",
  PROVINCES: "/provinces",
  GET_ORDERS_COUNT: "/business/orders/counts/get",
  GET_SUPPORTIVE_PACKAGES: "/business/support-packages",
  DAYLI_WORK: "/business/settings/daily-activity",
  SEND_TYPE: "/business/settings/send-type",
  ORDER_MIN_PRICE: "/business/settings/order-min-price",
  SALES_REPORT: "/business/accounting/sale-reports",
  SALES_REPORT_FILTER: "/business/accounting/sale-reports/filter",
  DISCOUT_COUPONS: "/business/settings/discount-coupons",
  BUSINESS_PRODUCTS: "/business/business-products",
  ALL_PRODUCTS: (string) => `/business/products${string ? `?${string}` : ""}`,
  USER_DISCOUT_COUPONS: "/business/settings/discount-coupon",
  PRODUCTS_MULTI: "/business/products/existing-multi",
  DAYLI_DISCOUNT: "/business/daily-discounts",
  USER_TAX: "/business/settings/tax",
  BUSINESS_STEP_ONE: "/business/products-step-one",
  BUSINESS_STEP_TWO: "/business/products-step-two",
  SUPPORT_STEP_ONE: "/business/support-packages/step-one",
  SUPPORT_STEP_TWO: "/business/support-packages/step-two",
  SUB_CATEGORIES: (id) => `/categories/${id}`,
  CATEGORIES: "/categories",
  BUSINESS_CATEGORIES: "/business/categories",
  REJECT_REASONS: "/business/orders/reject-orders/get",
  BUSINESS_COMMENTS: "/business/comments",
  BUSINESS_CATEGORIE: (id) => `/categories/${id}`,
  GET_ORDERS: (id) => `/business/orders?status=${id}`,
  GET_ORDER: (id) => `/business/orders/${id}`,

  ORDER_IS_READY: (id) => `/business/orders/${id}/prepared`,
  ORDER_SENT_BY_SHOP: (id) => `/business/orders/${id}/send`,
  ORDER_DELIVERED_BY_SHOP: (id) => `/business/orders/${id}/delivered`,
  ASK_FOR_DELIVERY: (id) => `/business/orders/${id}/find-payke`,
  CANCEL_DELIVERY_REQUEST: (id) => `/business/orders/${id}/cancel-payke`,
  DELIVERED_TO_DELIVERER: (id) => `/business/orders/${id}/deliver-to-payke`,
  SET_ORDER: (id) => `/business/orders/${id}/change-status`,
  CHANGE_STATUS: (id) => `/business/products/${id}/change-status`,
  CHANGE_COLOR: (id) => `/business/products/${id}/colors`,
  BRANDS: "/brands",
  COUNTRIES: "/countries",
  COLORS: "/colors",
  SEARCH: (string) => `/business/products${string ? `?${string}` : ""}`,
  SEARCH_TITLE: (string) => `/business/business-products?${string}`,
  SIMPLE_SEARCH_TITLE: `/business/business-products`,
  SEARCH_CATS: `/business/products`,
  PRODUCTS_STATISTICS: `/business/statistics`,
  PRODUCTS_STATISTICS_BEST_SELLING: `/business/statistics/best-selling`,
  PRODUCTS_STATISTICS_LOW_STOCK: `/business/statistics/low-stock`,
  DAYLI_ACTIVE_DISCOUNTS: `/business/daily-discounts/active`,
  DAYLI_DEACTIVE_DISCOUNTS: `/business/daily-discounts/expired`,
  DAYLI_REVIVAL_DISCOUNTS: `/business/daily-discounts/reviral`,
  DAYLI_DISABLE_DISCOUNTS: `/business/daily-discounts/change-status`,
  DISCOUNTS: `/business/products/discounted/get`,
  CONTRACT_CONFIRMATION: `/business/contract/verify`,
  DISCOUNTS_STOCK: `/business/products/discounted/stock`,
  DISCOUNTS_EDIT_STOCK: `/business/daily-discounts`,
  DISCOUNTS_DISCOUNT: `/business/products/discounted/discount`,
  BUSINESS_TYPES: `/business-types`,
  CASH_REQUEST: `/business/cash-requests`,
  CHANGE_PASSWORD: `/business/change-password`,
  GET_MESSAGES: "/business/messages",
  TICKET_LIST: "/business/tickets",
  GET_TICKET_TITLES: "/business/ticket-titles",
  BUSINESS_TURNOVER: "/business/turnovers",
  BUSINESS_UNREAD_MESSAGE_COUNTS: "/business/messages/unread/count",
};
